version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik/dynamic:/dynamic
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influx.rule=Host(`influxfinal.atherpulse.in`)"
      - "traefik.http.routers.influx.entrypoints=websecure"
      - "traefik.http.routers.influx.tls.certresolver=myresolver"

  fastapi:
    build: ./api
    container_name: fastapi
    networks:
      - web
    volumes:
      - ./api:/app     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`apifinal.atherpulse.in`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafanafinal.atherpulse.in`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"

  amardrop:
    image: amarjith9801/amardrop:v2.0
    container_name: amardrop
    ports:
      - "8005:8005"
    volumes:
      - ./amardrop/db:/app/db        # Mount database directory
      - ./amardrop/uploads:/app/uploads  # Mount uploads directory
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amardrop.rule=Host(`p.atherpulse.in`)"
      - "traefik.http.routers.amardrop.entrypoints=websecure"
      - "traefik.http.routers.amardrop.tls.certresolver=myresolver"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    volumes:
      - ./telegraf:/etc/telegraf
    
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegraf.rule=Host(`telegrafinal.atherpulse.in`)"
      - "traefik.http.routers.telegraf.entrypoints=websecure"
      - "traefik.http.routers.telegraf.tls.certresolver=myresolver"

networks:
  web:
    external: false
