version: "3.9"
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
    - DOCKER_INFLUXDB_INIT_ORG=myorg
    - DOCKER_INFLUXDB_INIT_BUCKET=energy
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

  fastapi:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      # Use the token you defined above
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=myorg
      - INFLUX_BUCKET=energy
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
